# Generated by Django 3.2.8 on 2021-11-10 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordbog_app', '0006_auto_20211110_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
